from ..algorithm import Node as Node
from ..search import SolutionOutputter as SolutionOutputter

SOLUTION_PATH_COLOR: str

class DotOutputter(SolutionOutputter):
    file: str
    def __init__(self, **kwargs) -> None: ...
    def output(self, solution): ...
    @staticmethod
    def get_node_attrs(node, problem, sol_path): ...
    @staticmethod
    def get_action_attrs(parent, child, path): ...
    @staticmethod
    def get_edge_attrs(parent, child, path): ...
