from _typeshed import Incomplete
from collections.abc import Generator

def print_columns(iterable, n_columns: int = 2, prefix: str = '', sep: int = 4, file=...) -> None: ...
def chunkify(iterable, size) -> Generator[Incomplete]: ...
