# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from os import environ
import collections

__version__ = f'{version_info.major}.{version_info.minor}.{version_info.micro}'
environ: 'hide'

__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import os
import collections
import argparse
import glob
import importlib
import importlib.machinery
import inspect
import logging
import sys
import hlogedu.__version__
import posixpath
import abc
import copy
import enum
import typing
import dataclasses
import __future__
import heapq
import graphviz
import itertools
import pygame